const FORMATS = {
  'formal-exam': {
    id: 'formal-exam',
    label: 'Formal Exam',
    icon: 'FileText',
    description: 'Locked-down, proctored exam with strict timing and single attempt.',
    badge: 'Locked',
    badgeClass: 'bg-red-500/15 text-red-400 border-red-500/20',
    defaults: {
      duration: 60,
      perQuestionTimer: 0,
      selfPaced: false,
      windowedSchedule: true,
      proctoring: {
        tabSwitchDetection: true,
        fullscreenEnforcement: true,
        rightClickBlock: true,
        copyPasteBlock: true,
        devtoolsBlock: true,
        webcam: false,
        maxTabSwitches: 3,
        autoSubmitAfterMax: true,
      },
      feedback: 'after-submission',
      showExplanations: false,
      showCorrectAnswers: false,
      navigation: 'free',
      allowBacktracking: true,
      scoring: {
        type: 'standard',
        passThreshold: 50,
        negativePerWrong: 0,
        partialCredit: false,
        speedScoring: false,
      },
      questionOrder: 'random',
      questionSelection: 'all',
      subsetCount: 0,
      maxAttempts: 1,
      resultsDisplay: 'full-review',
      showLeaderboard: false,
      mode: 'exam',
      collaboration: 'individual',
      audience: 'enrolled',
      hintsEnabled: false,
      referenceEnabled: true,
    },
  },

  'practice-quiz': {
    id: 'practice-quiz',
    label: 'Practice Quiz',
    icon: 'BookOpen',
    description: 'Low-stakes practice with instant feedback, hints, and unlimited attempts.',
    badge: 'Flexible',
    badgeClass: 'bg-emerald-500/15 text-emerald-400 border-emerald-500/20',
    defaults: {
      duration: 0,
      perQuestionTimer: 0,
      selfPaced: true,
      windowedSchedule: false,
      proctoring: {
        tabSwitchDetection: false,
        fullscreenEnforcement: false,
        rightClickBlock: false,
        copyPasteBlock: false,
        devtoolsBlock: false,
        webcam: false,
        maxTabSwitches: 99,
        autoSubmitAfterMax: false,
      },
      feedback: 'per-question',
      showExplanations: true,
      showCorrectAnswers: true,
      navigation: 'free',
      allowBacktracking: true,
      scoring: {
        type: 'standard',
        passThreshold: 0,
        negativePerWrong: 0,
        partialCredit: false,
        speedScoring: false,
      },
      questionOrder: 'random',
      questionSelection: 'all',
      subsetCount: 0,
      maxAttempts: 99,
      resultsDisplay: 'full-review',
      showLeaderboard: false,
      mode: 'practice',
      collaboration: 'individual',
      audience: 'self-study',
      hintsEnabled: true,
      referenceEnabled: true,
    },
  },

  'homework': {
    id: 'homework',
    label: 'Homework Assignment',
    icon: 'Timer',
    description: 'Extended deadline, open-book, multiple attempts, score-based grading.',
    badge: 'Extended',
    badgeClass: 'bg-amber-500/15 text-amber-400 border-amber-500/20',
    defaults: {
      duration: 0,
      perQuestionTimer: 0,
      selfPaced: true,
      windowedSchedule: true,
      proctoring: {
        tabSwitchDetection: false,
        fullscreenEnforcement: false,
        rightClickBlock: false,
        copyPasteBlock: false,
        devtoolsBlock: false,
        webcam: false,
        maxTabSwitches: 0,
        autoSubmitAfterMax: false,
      },
      feedback: 'after-submission',
      showExplanations: false,
      showCorrectAnswers: true,
      navigation: 'free',
      allowBacktracking: true,
      scoring: {
        type: 'standard',
        passThreshold: 50,
        negativePerWrong: 0,
        partialCredit: false,
        speedScoring: false,
      },
      questionOrder: 'fixed',
      questionSelection: 'all',
      subsetCount: 0,
      maxAttempts: 3,
      resultsDisplay: 'full-review',
      showLeaderboard: false,
      mode: 'exam',
      collaboration: 'individual',
      audience: 'enrolled',
      hintsEnabled: true,
      referenceEnabled: true,
    },
  },

  'survey': {
    id: 'survey',
    label: 'Survey / Poll',
    icon: 'BarChart3',
    description: 'Anonymous feedback collection, no scoring, aggregated results only.',
    badge: 'Anonymous',
    badgeClass: 'bg-indigo-500/15 text-indigo-400 border-indigo-500/20',
    defaults: {
      duration: 0,
      perQuestionTimer: 0,
      selfPaced: true,
      windowedSchedule: false,
      proctoring: {
        tabSwitchDetection: false,
        fullscreenEnforcement: false,
        rightClickBlock: false,
        copyPasteBlock: false,
        devtoolsBlock: false,
        webcam: false,
        maxTabSwitches: 0,
        autoSubmitAfterMax: false,
      },
      feedback: 'none',
      showExplanations: false,
      showCorrectAnswers: false,
      navigation: 'free',
      allowBacktracking: true,
      scoring: {
        type: 'none',
        passThreshold: 0,
        negativePerWrong: 0,
        partialCredit: false,
        speedScoring: false,
      },
      questionOrder: 'fixed',
      questionSelection: 'all',
      subsetCount: 0,
      maxAttempts: 1,
      resultsDisplay: 'aggregated',
      showLeaderboard: false,
      mode: 'exam',
      collaboration: 'individual',
      audience: 'public',
      hintsEnabled: false,
      referenceEnabled: false,
    },
  },
}

export const FORMAT_IDS = Object.keys(FORMATS)

export function getFormat(id) {
  return FORMATS[id] || null
}

export function getFormatDefaults(id) {
  const fmt = FORMATS[id]
  return fmt ? structuredClone(fmt.defaults) : null
}

export function getAllFormats() {
  return Object.values(FORMATS)
}

export default FORMATS
